name: Spawn
version: 1.6.1
main: spawn\Main
api: 3.17.5
author: LorenMCBE
commands:
  setspawn:
    description: Устанавливает точку спавна
    usage: /setspawn или /setspawn <x> <y> <z>
    permission: setspawn.use
    aliases: [setsp]
  spawn:
    description: Телепорт на спавн
    usage: /spawn
    permission: spawn.use
    aliases: [sp]
  
permissions:
  setspawn.use:
    default: op
  spawn.use:
    default: true
  